### ISSUE TITLE
Add section to list input files for all V&V cases

### ISSUE THREAD

**Issue by lin-yang-ly** [idaholab/TMAP8#167] opened 2024-09-09 20:18 UTC
## Reason
Hard to find the input files of some cases

## Design
Add input section in documentation

## Impact
Make the input files of each case easier to find in documentation

**Comment by simopier** [comment] 2024-09-24 18:02
Addressed in https://github.com/idaholab/TMAP8/pull/172, and duplicate of #150.

**Closed by simopier** 2024-09-24 18:02 UTC
Labels: documentation
